### ISSUE TITLE
Just an info :)

### ISSUE THREAD

**Issue by sigysmund** [gotthardp/meta-lorawan#1]
Hi,

I have put up a [OE layer](https://layers.openembedded.org/layerindex/branch/master/layer/meta-lora-net/), which provides lora-net packages,
maybe you will be willing to test it with your servers meta.

I will definitely test your layer how it goes with my image.

Thanks and GL

**Comment by gotthardp** [comment]
Thanks. I think it's an useful info, so I added a link to README.
