### ISSUE TITLE
Lorix One Integration & v0.5.0 update

### ISSUE THREAD

**Issue by hallard** [gotthardp/meta-lorawan#2]
Hi,
I've successfully integrated the lorawan-server into Multitech and on Lorix One gateway but I needed to do some changes for the Lorix One. Here the script I used

```shell
# Optionnal LoraWan Server
echo "Getting lorawan-server"
git clone https://github.com/gotthardp/meta-lorawan
LORABB=meta-lorawan/recipes-core/images/mlinux-lorawan-image.bb
sed -i -e 's/mlinux-base-image/core-image-base/g' $LORABB
sed -i -e 's/mLinux LoRaWAN image/yocto LoRaWAN image/g' $LORABB
sed -i '/\"mc\"/d' $LORABB #remove mc
sed -i '/lora-packet-forwarder-usb/d' $LORABB #remove USB packet forwarder
```
I do not know how it is possible to integrate changes in an easy way?
Anyway would it be possible to this meta repo to integrate V0.5.0?

Another strange thing, for this to works on Lorix One I needed to change `--chuid lorawan` by `-u lorawan`  in startup script `lorawan-server`, see this [ticket](https://github.com/gotthardp/lorawan-server/issues/255). Do you think it's safe to make this change on official repo?

thanks for your help

**Comment by gotthardp** [comment]
Oh, many thanks for testing this with lorix one!
Shouldn't there be a new image for lorixone with whatever settings it needs? I mean to have two images, one for mlinux the way it is and one for lorix with whatever changes worked you made?

BTW, you used one of the multitech's packet_forwarders also with lorix?

**Comment by hallard** [comment]
you're welcome, thanks for this great server ;-)
yeah 2 images sounds good to me, to be honest my knowledge of meta for yocto is not my best one, so I let you decide what's the best way to do.
I'm using the legacy packet forwarder (that is provided with the lorix). Since Lorix made this open source you can find the repo [there](https://github.com/Wifx/meta-wifx/tree/krogoth/recipes-connectivity)

But Yannick compiled the new one mp_pkt_fwd from [kersing](https://github.com/kersing/packet_forwarder) and it's working fine also.

**Comment by gotthardp** [comment]
I just made some updates, but I am unnable to test them now.

**Comment by hallard** [comment]
Ok, I tested compilation at first step, I noticed 2 things

- change `require wifx-base.bb` by `require recipes-core/images/core-image-base.bb` in file `recipes-core/images/wifx-server-image.bb` 
- needed to delete file `recipes-core/images/mlinux-lorawan-image.bb` because bitbake error on mlinux base not found, but this makes sense, maybe update the readme doc saying to just keep the file of the target we need to build.

After this, bitbake fetched v0.5.0, compiled fine, so should be good, I'll test this later ;-)

**Comment by gotthardp** [comment]
Thanks a lot. I was afraid of this error. One apparently cannot have mlinux and lorix support at the same time. I modified the repository and updated README accordingly.
